/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package map;
import edu.princeton.cs.introcs.*;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.lang.String;
import java.awt.*;
import java.util.*;

import edu.princeton.cs.introcs.StdDraw;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hcps-larochesp
 */
public class MapUI extends javax.swing.JDialog {
    File file;
    File file2;
    String state;
    String year;

    /**
     * Creates new form MapUI
     */
    public MapUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        createMap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        electYear = new javax.swing.JScrollPane();
        electionYear = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        mapType = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to the Political Map Maker");

        createMap.setBackground(new java.awt.Color(51, 255, 51));
        createMap.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        createMap.setText("Create Map");
        createMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        jLabel2.setText("Select the characteristics of your map with the options below");

        electionYear.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        electionYear.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1960", "1964", "1968", "1972", "1976", "1980", "1984", "1988", "1992", "1996", "2000", "2004", "2008", "2012" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        electYear.setViewportView(electionYear);

        mapType.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        mapType.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "USA", "USA-county", "AL", "AZ", "AK", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IN", "IL", "ID", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(mapType);

        jLabel3.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        jLabel3.setText("What do you want to draw?");

        jLabel4.setText("What voter data do you want to use?");

        error.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createMap)
                            .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(231, 231, 231))))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(electYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electYear, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(createMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMapActionPerformed
            Stack allStates = new Stack();
            String[] allStatesAry;
            String electionData;
            String[] dataLine;
            java.awt.Color stateColor;
            String subSection;
            String noRepeat = "";
            String subName = "";
            HashMap colorMap = new HashMap();
            HashMap colorHolder = new HashMap();
            FillStates phil = new FillStates();
            error.setText("");
            state = String.valueOf(mapType.getSelectedValue());
            year = String.valueOf(electionYear.getSelectedValue());
            String filePath;
            String filePath2;
            if(state.equals(null) || year.equals(null) || state.equals("") || year.equals("")){
                error.setText("No State Selected");
            }
            else{
                filePath = "src/data/" + state + ".txt";
                file = new File(filePath);
                if(state.equals("USA-county")){
                    Scanner scan;
                    String stateSym = "";
                    try {
                        scan = new Scanner(file.getAbsoluteFile());
                        while(scan.hasNext()){
                            if(scan.hasNextInt() || scan.hasNextDouble()){
                                scan.nextLine();
                            }
                            else{
                                scan.nextLine();
                                stateSym = scan.nextLine();
                                if(stateSym.length() > 2){
                                    stateSym = scan.nextLine();
                                }
                                
                                if(stateSym.equals(noRepeat)){
                                    scan.nextLine();
                                }
                                else{
                                    noRepeat = stateSym;
                                    filePath2 = "src/data/" + stateSym + year + ".txt";
                                    file2 = new File(filePath2);
                                    Scanner scan2 = new Scanner(file2.getAbsoluteFile());
                                    scan2.nextLine();
                                    int u = 0;
                                    while(scan2.hasNext()){
                                        scan2.nextLine();
                                        u++;
                                    }
                                    scan2 = new Scanner(file2.getAbsoluteFile());
                                    scan2.nextLine();
                                    for(int i = 0; i < u; i++){
                                        electionData = scan2.nextLine();
                                        dataLine = electionData.split(",");
                                        subSection = dataLine[0];
                                        int[] voterData = new int[3];
                                        voterData[0] = Integer.parseInt(dataLine[1]);
                                        voterData[1] = Integer.parseInt(dataLine[2]);
                                        voterData[2] = Integer.parseInt(dataLine[3]);
                                        stateColor = (phil.colorStates(voterData));
                                        colorHolder.put(subSection.toLowerCase(), stateColor);
                                        allStates.push(subSection.toLowerCase());
                                    }
                                }
                            }
                        }
                        allStatesAry = new String[allStates.size()];
                        int g = allStates.size();
                        for(int i = 0; i < g; i++){
                            allStatesAry[i] = (String)allStates.pop();
                        }
                        scan = new Scanner(file.getAbsoluteFile());
                        StdDraw.setCanvasSize(1200, 650);
                        StdDraw.setPenRadius(0.002);
                        StdDraw.setPenColor(java.awt.Color.BLACK);
                        double xMin = scan.nextDouble();
                        double yMin = scan.nextDouble();
                        double xMax = scan.nextDouble();
                        double yMax = scan.nextDouble();
                        int regionNum = scan.nextInt();
                        StdDraw.setXscale(xMin, xMax);
                        StdDraw.setYscale(yMin, yMax);
                        double[] xVal;
                        double[] yVal;
                        int pointNum = 0;
                        for(int i = 0; i < regionNum; i++){
                        if(scan.hasNextInt() == true){
                            pointNum = scan.nextInt();
                            xVal = new double[pointNum];
                            yVal = new double[pointNum];
                            for(int j = 0; j < pointNum; j++){
                               xVal[j] = scan.nextDouble();
                               yVal[j] = scan.nextDouble();
                            }   
                            boolean exists = false;
                            for(int p = 0; p < allStatesAry.length; p++){
                                if(subName.toLowerCase().equals(allStatesAry[p])){
                                    exists = true;
                                }
                                else{

                                }  
                            }    
                            
                            if(exists == true){
                                StdDraw.polygon(xVal, yVal);
                                StdDraw.setPenColor((Color)colorHolder.get(subName.toLowerCase()));
                                StdDraw.filledPolygon(xVal, yVal);
                                StdDraw.setPenColor(Color.BLACK);
                            }
                            else{
                                StdDraw.polygon(xVal, yVal);
                                StdDraw.filledPolygon(xVal, yVal);
                            }
                            
                        }
                        else{
                            i = i - 1;
                            boolean hasInput = false;
                            subName = scan.nextLine();
                            while(hasInput == false){
                                if(subName.equals("")){
                                    subName = scan.nextLine();
                                }
                                else{
                                    hasInput = true;
                                }
                            }
                            subName = subName.replace(" city", "");
                            subName = subName.replace(" Parish", "");
                            scan.nextLine();
                        }
                        }
                    }
                    catch (FileNotFoundException ex) {
                        Logger.getLogger(MapUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else{
                    filePath2 = "src/data/" + state + year + ".txt";
                    file2 = new File(filePath2);


                    Scanner scan;
                    Scanner scan2;
                    try {
                        scan = new Scanner(file.getAbsoluteFile());
                        scan2 = new Scanner(file2.getAbsoluteFile());
                        int u = 0;
                        scan2.nextLine();
                        while(scan2.hasNext() == true){
                            scan2.nextLine();
                            u++;
                        }
                        scan2 = new Scanner(file2.getAbsoluteFile());
                        String[] stateNames = new String[u];                    
                        scan2.nextLine();
                        for(int i = 0; i < u; i++){
                            electionData = scan2.nextLine();
                            dataLine = electionData.split(",");
                            subSection = dataLine[0].toLowerCase();
                            int[] voterData = new int[3];
                            voterData[0] = Integer.parseInt(dataLine[1]);
                            voterData[1] = Integer.parseInt(dataLine[2]);
                            voterData[2] = Integer.parseInt(dataLine[3]);
                            colorMap.put(subSection.toLowerCase(), voterData);
                            stateNames[i] = subSection.toLowerCase();
                        }

                        StdDraw.setCanvasSize(1200, 650);
                        StdDraw.setPenRadius(0.002);
                        StdDraw.setPenColor(java.awt.Color.BLACK);
                        double xMin = scan.nextDouble();
                        double yMin = scan.nextDouble();
                        double xMax = scan.nextDouble();
                        double yMax = scan.nextDouble();
                        int regionNum = scan.nextInt();
                        StdDraw.setXscale(xMin, xMax);
                        StdDraw.setYscale(yMin, yMax);
                        double[] xVal;
                        double[] yVal;
                        int pointNum = 0;
                        for(int i = 0; i < regionNum; i++){
                        if(scan.hasNextInt() == true){
                            pointNum = scan.nextInt();
                            xVal = new double[pointNum];
                            yVal = new double[pointNum];
                            for(int j = 0; j < pointNum; j++){
                               xVal[j] = scan.nextDouble();
                               yVal[j] = scan.nextDouble();
                            }    


                            StdDraw.polygon(xVal, yVal);

                            boolean exists = false;
                            for(int p = 0; p < stateNames.length; p++){
                                if(subName.toLowerCase().equals(stateNames[p])){
                                    exists = true;
                                }
                                else{

                                }
                            }

                            if(exists == true){
                                stateColor = (phil.colorStates((int[])colorMap.get(subName.toLowerCase())));
                                StdDraw.setPenColor(stateColor);
                                StdDraw.filledPolygon(xVal, yVal);
                                StdDraw.setPenColor(Color.BLACK);
                            }
                            else{
                                StdDraw.polygon(xVal, yVal);
                                StdDraw.filledPolygon(xVal, yVal);
                            }
                        }
                        else{
                            i = i - 1;
                            boolean hasInput = false;
                            subName = scan.nextLine();
                            while(hasInput == false){
                                if(subName.equals("")){
                                    subName = scan.nextLine();
                                }
                                else{
                                    hasInput = true;
                                }
                            }
                            subName = subName.replace(" city", "");
                            subName = subName.replace(" Parish", "");
                            scan.nextLine();
                        }
                    }
                    }
                    catch (FileNotFoundException ex) {
                        Logger.getLogger(MapUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
            
    }//GEN-LAST:event_createMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MapUI dialog = new MapUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createMap;
    private javax.swing.JScrollPane electYear;
    private javax.swing.JList electionYear;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList mapType;
    // End of variables declaration//GEN-END:variables
}
